# Generated by Django 5.2.11 on 2026-02-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_auditlog_delete_auditentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='document_id',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='metadata',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='changes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='model_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditlog',
            name='object_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(max_length=50),
        ),
    ]
